"""empty message

Revision ID: 14fe46262708
Revises: 23e11099b197
Create Date: 2019-09-13 01:35:40.875927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14fe46262708'
down_revision = '23e11099b197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'objects', ['status_of_the_report_id', 'type_object_id', 'city_id', 'region_id', 'street_type_id', 'street_id', 'settlement_area_id', 'category_id'])
    op.drop_column('objects', 'estimated_value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('estimated_value', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'objects', type_='unique')
    # ### end Alembic commands ###
