"""empty message

Revision ID: 1a08a007c44b
Revises: 2f7434df2918
Create Date: 2019-09-13 01:45:56.123362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a08a007c44b'
down_revision = '2f7434df2918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('estimated_value', sa.String(), nullable=True))
    op.drop_constraint('objects_status_of_the_report_id_type_object_id_city_id_regi_key', 'objects', type_='unique')
    op.create_unique_constraint(None, 'objects', ['estimated_value', 'status_of_the_report_id', 'type_object_id', 'city_id', 'region_id', 'street_type_id', 'street_id', 'category_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'objects', type_='unique')
    op.create_unique_constraint('objects_status_of_the_report_id_type_object_id_city_id_regi_key', 'objects', ['status_of_the_report_id', 'type_object_id', 'city_id', 'region_id', 'street_type_id', 'street_id', 'category_id'])
    op.drop_column('objects', 'estimated_value')
    # ### end Alembic commands ###
