"""empty message

Revision ID: 1a0eb174ae2c
Revises: 1a8f9243ccf5
Create Date: 2019-09-13 04:12:27.437773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a0eb174ae2c'
down_revision = '1a8f9243ccf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('city_id', sa.Integer(), nullable=True))
    op.add_column('objects', sa.Column('street_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'objects', 'streets', ['street_id'], ['id'])
    op.create_foreign_key(None, 'objects', 'cites', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'objects', type_='foreignkey')
    op.drop_constraint(None, 'objects', type_='foreignkey')
    op.drop_column('objects', 'street_id')
    op.drop_column('objects', 'city_id')
    # ### end Alembic commands ###
