"""empty message

Revision ID: 1a8f9243ccf5
Revises: 6718587fe999
Create Date: 2019-09-13 03:38:58.068405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a8f9243ccf5'
down_revision = '6718587fe999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('streets_street_key', 'streets', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('streets_street_key', 'streets', ['street'])
    # ### end Alembic commands ###
