"""empty message

Revision ID: 1eb1d391ace8
Revises: ddc08a800e05
Create Date: 2019-09-20 18:03:37.936858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eb1d391ace8'
down_revision = 'ddc08a800e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('addresses_location_id_fkey', 'addresses', type_='foreignkey')
    op.create_foreign_key(None, 'addresses', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.create_foreign_key('addresses_location_id_fkey', 'addresses', 'users', ['location_id'], ['id'])
    # ### end Alembic commands ###
