"""empty message

Revision ID: 23e11099b197
Revises: 5bd6780d6ab1
Create Date: 2019-09-13 01:09:04.763253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e11099b197'
down_revision = '5bd6780d6ab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint(None, 'objects', ['estimated_value', 'status_of_the_report_id', 'type_object_id', 'city_id', 'region_id', 'street_type_id', 'street_id', 'settlement_area_id', 'category_id'])
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'objects', type_='unique')
    # ### end Alembic commands ###
    pass
