"""empty message

Revision ID: 30444d65aaaf
Revises: 61334a571811
Create Date: 2019-09-13 02:53:25.838853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30444d65aaaf'
down_revision = '61334a571811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cites_region_id_fkey', 'cites', type_='foreignkey')
    op.create_foreign_key(None, 'cites', 'regions', ['region_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cites', type_='foreignkey')
    op.create_foreign_key('cites_region_id_fkey', 'cites', 'cites', ['region_id'], ['id'])
    # ### end Alembic commands ###
