"""empty message

Revision ID: 47e06af68e7b
Revises: e9133a5d554d
Create Date: 2019-09-23 12:13:09.844961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e06af68e7b'
down_revision = 'e9133a5d554d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('photo_id', sa.Integer(), nullable=True))
    op.drop_constraint('images_url_key', 'images', type_='unique')
    op.create_unique_constraint(None, 'images', ['photo_id'])
    op.create_unique_constraint(None, 'images', ['id'])
    op.drop_column('images', 'url')
    op.drop_column('images', 'count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('images', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'images', type_='unique')
    op.drop_constraint(None, 'images', type_='unique')
    op.create_unique_constraint('images_url_key', 'images', ['url'])
    op.drop_column('images', 'photo_id')
    # ### end Alembic commands ###
