"""empty message

Revision ID: 47e49b1c47fe
Revises: d36b40ba5c90
Create Date: 2019-09-20 21:57:22.641666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e49b1c47fe'
down_revision = 'd36b40ba5c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checks', sa.Column('telegram_shop_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'checks', 'checks', ['telegram_shop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'checks', type_='foreignkey')
    op.drop_column('checks', 'telegram_shop_id')
    # ### end Alembic commands ###
