"""empty message

Revision ID: 49cc085ef589
Revises: 92252e237959
Create Date: 2019-09-23 10:30:25.926109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49cc085ef589'
down_revision = '92252e237959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('users', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'admins', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'admin_id')
    op.drop_table('admins')
    # ### end Alembic commands ###
