"""empty message

Revision ID: 5bd6780d6ab1
Revises: 919e52f0cbe4
Create Date: 2019-09-13 00:25:08.573275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd6780d6ab1'
down_revision = '919e52f0cbe4'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('settlement_areas')
    # op.drop_constraint('objects_settlement_area_id_fkey', 'objects', type_='foreignkey')
    # op.drop_column('objects', 'settlement_area_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('settlement_area_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('objects_settlement_area_id_fkey', 'objects', 'settlement_areas', ['settlement_area_id'], ['id'])
    op.create_table('settlement_areas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('settlement_area', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='settlement_areas_pkey'),
    sa.UniqueConstraint('settlement_area', name='settlement_areas_settlement_area_key')
    )
    # ### end Alembic commands ###
