"""empty message

Revision ID: 61334a571811
Revises: d908837cf118
Create Date: 2019-09-13 02:44:44.141071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61334a571811'
down_revision = 'd908837cf118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cites', ['city', 'region_id'])
    op.create_unique_constraint(None, 'streets', ['street', 'city_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'streets', type_='unique')
    op.drop_constraint(None, 'cites', type_='unique')
    # ### end Alembic commands ###
