"""empty message

Revision ID: 6718587fe999
Revises: e8baa2a6e51a
Create Date: 2019-09-13 03:31:37.548293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6718587fe999'
down_revision = 'e8baa2a6e51a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    pass
