"""empty message

Revision ID: 69c10b953abe
Revises: dc26ac8e55f9
Create Date: 2019-10-01 13:34:09.338929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69c10b953abe'
down_revision = 'dc26ac8e55f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viewed__telegram_shops',
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('telegram_shops_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['telegram_shops_id'], ['telegram_shops.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.UniqueConstraint('users_id', 'telegram_shops_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viewed__telegram_shops')
    # ### end Alembic commands ###
