"""empty message

Revision ID: 81cbfc9e2e45
Revises: a0422c974467
Create Date: 2019-09-20 09:50:01.338238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72c691b67948'
down_revision = '418404d117a7'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('shops', sa.Column('checked_by_admin', sa.Boolean(), nullable=True))
    # op.add_column('shops', sa.Column('hide', sa.Boolean(), nullable=True))
    # op.drop_column('shops', 'valid')
    # op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'users', type_='unique')
    # op.add_column('shops', sa.Column('valid', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # op.drop_column('shops', 'hide')
    # op.drop_column('shops', 'checked_by_admin')
    # ### end Alembic commands ###
