"""empty message

Revision ID: 85b688755ae9
Revises: 69c10b953abe
Create Date: 2019-10-01 23:14:24.710124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b688755ae9'
down_revision = '69c10b953abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viewed__telegram_shops')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viewed__telegram_shops',
    sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('telegram_shops_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['telegram_shops_id'], ['telegram_shops.id'], name='viewed__telegram_shops_telegram_shops_id_fkey'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name='viewed__telegram_shops_users_id_fkey'),
    sa.UniqueConstraint('users_id', 'telegram_shops_id', name='viewed__telegram_shops_users_id_telegram_shops_id_key')
    )
    # ### end Alembic commands ###
