"""empty message

Revision ID: 919e52f0cbe4
Revises: e1e7eb601b14
Create Date: 2019-09-12 23:12:20.611311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '919e52f0cbe4'
down_revision = 'e1e7eb601b14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'objects', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'objects', type_='foreignkey')
    op.drop_column('objects', 'category_id')
    # ### end Alembic commands ###
