"""empty message

Revision ID: 92252e237959
Revises: ce860c78b683
Create Date: 2019-09-21 10:28:56.178518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92252e237959'
down_revision = 'ce860c78b683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('telegram_shops', sa.Column('block_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'telegram_shops', 'blocks', ['block_id'], ['id'])
    op.drop_column('telegram_shops', 'blocked')
    op.drop_column('telegram_shops', 'time_stamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_shops', sa.Column('time_stamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('telegram_shops', sa.Column('blocked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'telegram_shops', type_='foreignkey')
    op.drop_column('telegram_shops', 'block_id')
    op.drop_table('blocks')
    # ### end Alembic commands ###
