"""empty message

Revision ID: a0422c974467
Revises: 
Create Date: 2019-09-18 12:29:47.630149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0422c974467'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('activist', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    op.create_table('users__shops',
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('shops_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shops_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.UniqueConstraint('users_id', 'shops_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users__shops')
    op.drop_table('shops')
    op.drop_table('users')
    # ### end Alembic commands ###
