"""empty message

Revision ID: a8e15ccd3aa5
Revises: 30444d65aaaf
Create Date: 2019-09-13 02:59:49.542646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8e15ccd3aa5'
down_revision = '30444d65aaaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions__cites',
    sa.Column('regions_id', sa.Integer(), nullable=True),
    sa.Column('cites_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cites_id'], ['cites.id'], ),
    sa.ForeignKeyConstraint(['regions_id'], ['regions.id'], ),
    sa.UniqueConstraint('regions_id', 'cites_id')
    )
    op.create_table('streets__cites',
    sa.Column('streets_id', sa.Integer(), nullable=True),
    sa.Column('cites_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cites_id'], ['cites.id'], ),
    sa.ForeignKeyConstraint(['streets_id'], ['streets.id'], ),
    sa.UniqueConstraint('streets_id', 'cites_id')
    )
    op.drop_constraint('cites_city_region_id_key', 'cites', type_='unique')
    op.drop_constraint('cites_region_id_fkey', 'cites', type_='foreignkey')
    op.drop_column('cites', 'region_id')
    op.drop_constraint('streets_street_city_id_key', 'streets', type_='unique')
    op.drop_constraint('streets_city_id_fkey', 'streets', type_='foreignkey')
    op.drop_column('streets', 'city_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streets', sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('streets_city_id_fkey', 'streets', 'cites', ['city_id'], ['id'])
    op.create_unique_constraint('streets_street_city_id_key', 'streets', ['street', 'city_id'])
    op.add_column('cites', sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cites_region_id_fkey', 'cites', 'regions', ['region_id'], ['id'])
    op.create_unique_constraint('cites_city_region_id_key', 'cites', ['city', 'region_id'])
    op.drop_table('streets__cites')
    op.drop_table('regions__cites')
    # ### end Alembic commands ###
