"""empty message

Revision ID: bf1a9db21afa
Revises: 47e06af68e7b
Create Date: 2019-09-23 13:14:32.989500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf1a9db21afa'
down_revision = '47e06af68e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('photo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='images_pkey'),
    sa.UniqueConstraint('id', name='images_id_key'),
    sa.UniqueConstraint('photo_id', name='images_photo_id_key')
    )
    # ### end Alembic commands ###
