"""empty message

Revision ID: c2c646d8446f
Revises: 04050a9dd00c
Create Date: 2019-10-14 02:40:45.674176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2c646d8446f'
down_revision = '04050a9dd00c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_shops', sa.Column('valid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_shops', 'valid')
    # ### end Alembic commands ###
