"""empty message

Revision ID: ce860c78b683
Revises: e6515d74324f
Create Date: 2019-09-20 23:41:31.821375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce860c78b683'
down_revision = 'e6515d74324f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checks')
    op.add_column('telegram_shops', sa.Column('blocked', sa.Boolean(), nullable=True))
    op.add_column('telegram_shops', sa.Column('hide', sa.Boolean(), nullable=True))
    op.add_column('telegram_shops', sa.Column('time_stamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_shops', 'time_stamp')
    op.drop_column('telegram_shops', 'hide')
    op.drop_column('telegram_shops', 'blocked')
    op.create_table('checks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('blocked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('hide', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('time_stamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('telegram_shop_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['telegram_shop_id'], ['telegram_shops.id'], name='checks_telegram_shop_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='checks_pkey')
    )
    # ### end Alembic commands ###
