"""empty message

Revision ID: d36b40ba5c90
Revises: 1eb1d391ace8
Create Date: 2019-09-20 20:19:28.265559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd36b40ba5c90'
down_revision = '1eb1d391ace8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users__shops', sa.Column('telegram_shops_id', sa.Integer(), nullable=True))
    op.drop_constraint('users__shops_users_id_shops_id_key', 'users__shops', type_='unique')
    op.create_unique_constraint(None, 'users__shops', ['users_id', 'telegram_shops_id'])
    op.drop_constraint('users__shops_shops_id_fkey', 'users__shops', type_='foreignkey')
    op.create_foreign_key(None, 'users__shops', 'telegram_shops', ['telegram_shops_id'], ['id'])
    op.drop_column('users__shops', 'shops_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users__shops', sa.Column('shops_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users__shops', type_='foreignkey')
    op.create_foreign_key('users__shops_shops_id_fkey', 'users__shops', 'shops', ['shops_id'], ['id'])
    op.drop_constraint(None, 'users__shops', type_='unique')
    op.create_unique_constraint('users__shops_users_id_shops_id_key', 'users__shops', ['users_id', 'shops_id'])
    op.drop_column('users__shops', 'telegram_shops_id')
    # ### end Alembic commands ###
