"""empty message

Revision ID: d616f6d6a24e
Revises: 85b688755ae9
Create Date: 2019-10-10 13:33:23.765688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd616f6d6a24e'
down_revision = '85b688755ae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('inviter_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['inviter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'inviter_id')
    # ### end Alembic commands ###
