"""empty message

Revision ID: d908837cf118
Revises: 1a08a007c44b
Create Date: 2019-09-13 02:31:11.377734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd908837cf118'
down_revision = '1a08a007c44b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cites', sa.Column('region_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cites', 'cites', ['region_id'], ['id'])
    op.drop_constraint('objects_estimated_value_status_of_the_report_id_type_object_key', 'objects', type_='unique')
    op.create_unique_constraint(None, 'objects', ['estimated_value', 'status_of_the_report_id', 'type_object_id', 'category_id'])
    op.drop_constraint('objects_street_id_fkey', 'objects', type_='foreignkey')
    op.drop_constraint('objects_city_id_fkey', 'objects', type_='foreignkey')
    op.drop_constraint('objects_street_type_id_fkey', 'objects', type_='foreignkey')
    op.drop_column('objects', 'street_type_id')
    op.drop_column('objects', 'street_id')
    op.drop_column('objects', 'city_id')
    op.add_column('streets', sa.Column('city_id', sa.Integer(), nullable=True))
    op.add_column('streets', sa.Column('street_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'streets', 'street_types', ['street_type_id'], ['id'])
    op.create_foreign_key(None, 'streets', 'cites', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'streets', type_='foreignkey')
    op.drop_constraint(None, 'streets', type_='foreignkey')
    op.drop_column('streets', 'street_type_id')
    op.drop_column('streets', 'city_id')
    op.add_column('objects', sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('objects', sa.Column('street_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('objects', sa.Column('street_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('objects_street_type_id_fkey', 'objects', 'street_types', ['street_type_id'], ['id'])
    op.create_foreign_key('objects_city_id_fkey', 'objects', 'cites', ['city_id'], ['id'])
    op.create_foreign_key('objects_street_id_fkey', 'objects', 'streets', ['street_id'], ['id'])
    op.drop_constraint(None, 'objects', type_='unique')
    op.create_unique_constraint('objects_estimated_value_status_of_the_report_id_type_object_key', 'objects', ['estimated_value', 'status_of_the_report_id', 'type_object_id', 'city_id', 'region_id', 'street_type_id', 'street_id', 'category_id'])
    op.drop_constraint(None, 'cites', type_='foreignkey')
    op.drop_column('cites', 'region_id')
    # ### end Alembic commands ###
