"""empty message

Revision ID: dc26ac8e55f9
Revises: 71d5025ed7f0
Create Date: 2019-09-24 08:42:17.434710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc26ac8e55f9'
down_revision = '71d5025ed7f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'images', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='unique')
    # ### end Alembic commands ###
