"""empty message

Revision ID: ddc08a800e05
Revises: 538eef448b4c
Create Date: 2019-09-20 17:56:23.407107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddc08a800e05'
down_revision = '538eef448b4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.Column('hide', sa.Boolean(), nullable=True),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('latitude'),
    sa.UniqueConstraint('longitude')
    )
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_table('telegram_shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_link', sa.String(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('check_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['check_id'], ['checks.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_link')
    )
    op.create_table('web_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_address', sa.String(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_address')
    )
    op.drop_constraint('shops_link_key', 'shops', type_='unique')
    op.drop_column('shops', 'link')
    op.drop_column('shops', 'hide')
    op.drop_column('shops', 'available')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('available', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('shops', sa.Column('hide', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('shops', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('shops_link_key', 'shops', ['link'])
    op.drop_table('web_addresses')
    op.drop_table('telegram_shops')
    op.drop_table('addresses')
    op.drop_table('locations')
    op.drop_table('checks')
    # ### end Alembic commands ###
