"""users table

Revision ID: e008ca29ba32
Revises: 72c691b67948
Create Date: 2019-10-13 13:42:54.104322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e008ca29ba32'
down_revision = '72c691b67948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users__telegram_shops',
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('telegram_shops_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['telegram_shops_id'], ['telegram_shops.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.UniqueConstraint('users_id', 'telegram_shops_id')
    )
    op.drop_table('users__shops')
    op.add_column('admins', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('admins', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.add_column('admins', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_column('admins', 'username')
    op.drop_column('admins', 'password_hash')
    op.drop_column('admins', 'email')
    op.create_table('users__shops',
    sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('telegram_shops_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['telegram_shops_id'], ['telegram_shops.id'], name='users__shops_telegram_shops_id_fkey'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name='users__shops_users_id_fkey'),
    sa.UniqueConstraint('users_id', 'telegram_shops_id', name='users__shops_users_id_telegram_shops_id_key')
    )
    op.drop_table('users__telegram_shops')
    # ### end Alembic commands ###
