"""empty message

Revision ID: e6515d74324f
Revises: f1a1adf797cf
Create Date: 2019-09-20 22:05:21.935177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6515d74324f'
down_revision = 'f1a1adf797cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('checks_telegram_shop_id_fkey', 'checks', type_='foreignkey')
    op.create_foreign_key(None, 'checks', 'telegram_shops', ['telegram_shop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'checks', type_='foreignkey')
    op.create_foreign_key('checks_telegram_shop_id_fkey', 'checks', 'checks', ['telegram_shop_id'], ['id'])
    # ### end Alembic commands ###
