"""empty message

Revision ID: f1a1adf797cf
Revises: 47e49b1c47fe
Create Date: 2019-09-20 22:00:18.099016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a1adf797cf'
down_revision = '47e49b1c47fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('telegram_shops_check_id_fkey', 'telegram_shops', type_='foreignkey')
    op.drop_column('telegram_shops', 'check_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_shops', sa.Column('check_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('telegram_shops_check_id_fkey', 'telegram_shops', 'checks', ['check_id'], ['id'])
    # ### end Alembic commands ###
